### ISSUE TITLE
onPreInit Issues

### ISSUE THREAD

**Issue by alexgenovese** [ueno-llc/ueno-gatsby-starter#5]
Hi, 

I tried to run it, after "npm install", but I got these following errors:

`
sharp:45566): GLib-GObject-WARNING **: 11:43:20.149: cannot register existing type 'VipsObject'
(sharp:45566): GLib-CRITICAL **: 11:43:20.150: g_once_init_leave: assertion 'result != 0' failed

(sharp:45566): GLib-GObject-CRITICAL **: 11:43:20.150: g_type_register_static: assertion 'parent_type > 0' failed

(sharp:45566): GLib-CRITICAL **: 11:43:20.150: g_once_init_leave: assertion 'result != 0' failed
`

Do you know what does they refer to?

**Comment by jeremybarbet** [comment]
Hi,

I will close this issue. We published new version for our starters and it would be most likely fixed now. Just let us know. Usage to create project: `npx create-ueno-app gatsby my-app`
