### ISSUE TITLE
Broken on latest Gatsby release

### ISSUE THREAD

**Issue by chmac** [ueno-llc/ueno-gatsby-starter#6]
I tried upgrading this like `yarn upgrade --latest` and all kinds of stuff breaks. Looks like the `gatsby-plugin-ueno` is not compatible with the latest Gatsby release, then there's an issue with typescript imports. Guess this isn't compatible with the latest Gatsby release.

**Comment by 0x73706f6f6b** [comment]
Hmm same for me. I managed to fix one of the issues on my end by creating a new gatsby build and copying over the dependencies from their `template-www`. 

I pinpointed it to an issue with the sass-loader latest version options, downgrading to the v7.x.x solved it for me.

**Comment by jeremybarbet** [comment]
Hi!

We released new major version for our starters. We removed dependency to `gatsby-plugin-ueno` and to `template-www`. Your issue should be fixed by now. You can bootstrap a project by doing `npx create-ueno-app gatsby my-app`
