### ISSUE TITLE
Recommended install not working

### ISSUE THREAD

**Issue by DaliborIlic** [ueno-llc/ueno-gatsby-starter#9]
Hello nice people @UENO, both:
yarn create ueno-app <stack> project-name <style>
npx create-ueno-app <stack> project-name <style>
return an error:

`
(node:5648) UnhandledPromiseRejectionWarning: Error:
      ———————————————————————————————————————————————————————————

      Installing globally create-ueno-app as a package has been
      deprecated. Please now use yarn create ueno-app <gatsby|next|cra|native> my-app <sass|styled>.

      ———————————————————————————————————————————————————————————

    at checkForUpdate (C:\Users\User\AppData\Local\Yarn\Data\global\node_modules\create-ueno-app\lib\utils\check-for-update.js:27:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
`

Tried "gatsby", "cra" for <stack>, "sass" for <style>, tried omitting style altogether... No luck. Same error every time.

npx gatsby new my-app "https://github.com/ueno-llc/ueno-gatsby-starter#master" works.

Thanks!

**Comment by jeremybarbet** [comment]
Hi, 

Thanks for reporting. It has been fixed on latest version of `create-ueno-app@2.1.2`
